<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{ userId: string }>()

const storageKey = `ai_disclosure_accepted:${props.userId}`

const visible = ref(localStorage.getItem(storageKey) !== 'true')

const dismiss = () => {
    localStorage.setItem(storageKey, 'true')
    visible.value = false
}
</script>

<template>
    <Transition name="banner">
        <div v-if="visible" class="ai-disclosure-banner" role="banner" aria-live="polite">
            <div class="banner-content">
                <svg
                    class="banner-icon"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="18"
                    height="18"
                    fill="currentColor"
                    aria-hidden="true"
                >
                    <path
                        d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"
                    />
                </svg>
                <p class="banner-text">
                    Content in this app is generated by AI and may contain errors. It is not
                    professional advice — verify independently for critical decisions.
                    <router-link to="/ai-policy" class="banner-link" @click="dismiss">
                        AI &amp; Content Policy
                    </router-link>
                </p>
            </div>
            <button class="banner-dismiss" @click="dismiss" aria-label="Dismiss">
                Got it
            </button>
        </div>
    </Transition>
</template>

<style scoped>
.ai-disclosure-banner {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 1100;
    background-color: var(--bg-secondary);
    border-top: 1px solid var(--border-color);
    padding: 12px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
}

.banner-content {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    flex: 1;
    min-width: 0;
}

.banner-icon {
    color: var(--accent-color);
    flex-shrink: 0;
    margin-top: 1px;
}

.banner-text {
    font-size: calc(13px * var(--app-font-scale, 1));
    line-height: 1.5;
    color: var(--text-secondary);
    margin: 0;
}

.banner-link {
    color: var(--accent-color);
    text-decoration: none;
    white-space: nowrap;
    margin-left: 4px;
    transition: opacity 0.15s ease;
}

.banner-link:hover {
    opacity: 0.8;
    text-decoration: underline;
}

.banner-dismiss {
    flex-shrink: 0;
    padding: 6px 14px;
    background-color: var(--accent-color);
    color: #fff;
    border: none;
    border-radius: 6px;
    font-size: calc(13px * var(--app-font-scale, 1));
    font-weight: 500;
    cursor: pointer;
    transition: opacity 0.15s ease;
}

.banner-dismiss:hover {
    opacity: 0.85;
}

/* Slide-up enter/leave */
.banner-enter-active,
.banner-leave-active {
    transition: transform 0.25s ease, opacity 0.25s ease;
}

.banner-enter-from,
.banner-leave-to {
    transform: translateY(100%);
    opacity: 0;
}

@media (max-width: 600px) {
    .ai-disclosure-banner {
        flex-direction: column;
        align-items: flex-start;
        padding: 12px 16px;
        gap: 10px;
    }

    .banner-dismiss {
        align-self: flex-end;
    }
}
</style>
